"""add flight time mapping columns

Revision ID: 746482313895
Revises: 234b9a823f84
Create Date: 2026-02-21 02:17:29.803766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746482313895'
down_revision: Union[str, None] = '234b9a823f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_offers', sa.Column('departure_time', sa.DateTime(), nullable=False))
    op.add_column('flight_offers', sa.Column('arrival_time', sa.DateTime(), nullable=False))
    op.add_column('flight_offers', sa.Column('stops', sa.Integer(), nullable=False))
    op.add_column('flight_offers', sa.Column('duration', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight_offers', 'duration')
    op.drop_column('flight_offers', 'stops')
    op.drop_column('flight_offers', 'arrival_time')
    op.drop_column('flight_offers', 'departure_time')
    # ### end Alembic commands ###
