"""Add nullable offer_hash column

Revision ID: c460a86cdd55
Revises: 746482313895
Create Date: 2026-02-21 02:56:15.685187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c460a86cdd55'
down_revision: Union[str, None] = '746482313895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_offers', sa.Column('offer_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight_offers', 'offer_hash')
    # ### end Alembic commands ###
