"""Add model_registry table for ML deployment gates

Revision ID: 1183f2f35d75
Revises: d8f164ea3af3
Create Date: 2026-02-21 22:50:21.873823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1183f2f35d75'
down_revision: Union[str, None] = 'd8f164ea3af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('train_r2', sa.Float(), nullable=True),
    sa.Column('test_r2', sa.Float(), nullable=True),
    sa.Column('test_mae', sa.Float(), nullable=True),
    sa.Column('test_rmse', sa.Float(), nullable=True),
    sa.Column('deployed', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('is_candidate', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_version')
    )
    op.create_index(op.f('ix_model_registry_id'), 'model_registry', ['id'], unique=False)
    op.create_index('one_deployed_model', 'model_registry', ['deployed'], unique=True, postgresql_where=sa.text('deployed = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('one_deployed_model', table_name='model_registry', postgresql_where=sa.text('deployed = true'))
    op.drop_index(op.f('ix_model_registry_id'), table_name='model_registry')
    op.drop_table('model_registry')
    # ### end Alembic commands ###
