"""Add airline differentiation metadata and indexes

Revision ID: 1de3995d349d
Revises: ff63c3e85eb1
Create Date: 2026-02-21 20:55:57.922260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de3995d349d'
down_revision: Union[str, None] = 'ff63c3e85eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_offers', sa.Column('number_of_bookable_seats', sa.Integer(), nullable=True))
    op.add_column('flight_offers', sa.Column('cabin_class', sa.String(length=50), nullable=True))
    op.add_column('flight_offers', sa.Column('fare_basis', sa.String(length=50), nullable=True))
    op.create_index('idx_route_airline_created', 'flight_offers', ['origin', 'destination', 'airline', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_route_airline_created', table_name='flight_offers')
    op.drop_column('flight_offers', 'fare_basis')
    op.drop_column('flight_offers', 'cabin_class')
    op.drop_column('flight_offers', 'number_of_bookable_seats')
    # ### end Alembic commands ###
