"""create flight_offers table

Revision ID: 234b9a823f84
Revises: 
Create Date: 2026-02-21 02:02:18.713813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '234b9a823f84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('departure_date', sa.DateTime(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('airline', sa.String(length=100), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_origin_destination_dep', 'flight_offers', ['origin', 'destination', 'departure_date'], unique=False)
    op.create_index(op.f('ix_flight_offers_created_at'), 'flight_offers', ['created_at'], unique=False)
    op.create_index(op.f('ix_flight_offers_departure_date'), 'flight_offers', ['departure_date'], unique=False)
    op.create_index(op.f('ix_flight_offers_destination'), 'flight_offers', ['destination'], unique=False)
    op.create_index(op.f('ix_flight_offers_id'), 'flight_offers', ['id'], unique=False)
    op.create_index(op.f('ix_flight_offers_origin'), 'flight_offers', ['origin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_offers_origin'), table_name='flight_offers')
    op.drop_index(op.f('ix_flight_offers_id'), table_name='flight_offers')
    op.drop_index(op.f('ix_flight_offers_destination'), table_name='flight_offers')
    op.drop_index(op.f('ix_flight_offers_departure_date'), table_name='flight_offers')
    op.drop_index(op.f('ix_flight_offers_created_at'), table_name='flight_offers')
    op.drop_index('idx_origin_destination_dep', table_name='flight_offers')
    op.drop_table('flight_offers')
    # ### end Alembic commands ###
