"""Add collector_state table for api rotation

Revision ID: 269a570b45ee
Revises: be3854f7ac78
Create Date: 2026-02-21 22:14:06.611686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '269a570b45ee'
down_revision: Union[str, None] = 'be3854f7ac78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_route_offset', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collector_state_id'), 'collector_state', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collector_state_id'), table_name='collector_state')
    op.drop_table('collector_state')
    # ### end Alembic commands ###
