"""Add Airport schema and distance_km

Revision ID: 299fc76b2eb7
Revises: 418a7ddd56ba
Create Date: 2026-02-21 17:40:41.960593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299fc76b2eb7'
down_revision: Union[str, None] = '418a7ddd56ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
