"""Set offer_hash strictly unique

Revision ID: 418a7ddd56ba
Revises: c460a86cdd55
Create Date: 2026-02-21 02:57:20.324526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '418a7ddd56ba'
down_revision: Union[str, None] = 'c460a86cdd55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flight_offers', 'offer_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.create_index(op.f('ix_flight_offers_offer_hash'), 'flight_offers', ['offer_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_offers_offer_hash'), table_name='flight_offers')
    op.alter_column('flight_offers', 'offer_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
