"""Add comparison columns model_registry

Revision ID: 6386c72e1d26
Revises: 1183f2f35d75
Create Date: 2026-02-21 23:21:36.395180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6386c72e1d26'
down_revision: Union[str, None] = '1183f2f35d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_registry', sa.Column('compared_against_version', sa.String(length=50), nullable=True))
    op.add_column('model_registry', sa.Column('compared_on_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_registry', 'compared_on_timestamp')
    op.drop_column('model_registry', 'compared_against_version')
    # ### end Alembic commands ###
