"""Add routes_master table

Revision ID: be3854f7ac78
Revises: 1de3995d349d
Create Date: 2026-02-21 21:49:24.127133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3854f7ac78'
down_revision: Union[str, None] = '1de3995d349d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('discovered_from_hub', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_master_active'), 'routes_master', ['active'], unique=False)
    op.create_index(op.f('ix_routes_master_destination'), 'routes_master', ['destination'], unique=False)
    op.create_index(op.f('ix_routes_master_origin'), 'routes_master', ['origin'], unique=False)
    op.drop_index('idx_created_at', table_name='flight_offers')
    op.drop_index('idx_route_airline_time', table_name='flight_offers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_route_airline_time', 'flight_offers', [sa.text("((origin::text || '-'::text) || destination::text)"), 'airline', 'created_at'], unique=False)
    op.create_index('idx_created_at', 'flight_offers', ['created_at'], unique=False)
    op.drop_index(op.f('ix_routes_master_origin'), table_name='routes_master')
    op.drop_index(op.f('ix_routes_master_destination'), table_name='routes_master')
    op.drop_index(op.f('ix_routes_master_active'), table_name='routes_master')
    op.drop_table('routes_master')
    # ### end Alembic commands ###
