"""Add quota tracking columns to collector_state

Revision ID: d8f164ea3af3
Revises: 269a570b45ee
Create Date: 2026-02-21 22:33:03.742300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f164ea3af3'
down_revision: Union[str, None] = '269a570b45ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collector_state', sa.Column('api_calls_today', sa.Integer(), server_default='0', nullable=False))
    op.add_column('collector_state', sa.Column('last_run_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collector_state', 'last_run_date')
    op.drop_column('collector_state', 'api_calls_today')
    # ### end Alembic commands ###
