"""Add Airport table and distance_km

Revision ID: ff63c3e85eb1
Revises: 299fc76b2eb7
Create Date: 2026-02-21 17:41:19.040152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff63c3e85eb1'
down_revision: Union[str, None] = '299fc76b2eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airports',
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('iata_code')
    )
    op.create_index(op.f('ix_airports_iata_code'), 'airports', ['iata_code'], unique=False)
    op.add_column('flight_offers', sa.Column('distance_km', sa.Float(), nullable=True))
    op.create_index(op.f('ix_flight_offers_distance_km'), 'flight_offers', ['distance_km'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_offers_distance_km'), table_name='flight_offers')
    op.drop_column('flight_offers', 'distance_km')
    op.drop_index(op.f('ix_airports_iata_code'), table_name='airports')
    op.drop_table('airports')
    # ### end Alembic commands ###
